#I got help with this part of the code by Frans Hånes, therfore we have similar code

controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints: [motor_joint, indicator_joint]
      gains:
        motor_joint:
          p: 0.1
          i: 0.01
          d: 0.001